server:
  port: 9090

spring:

  application:
    name: springboot-blog-api-simple
  
  datasource:
      url: jdbc:mysql://localhost:13306/simpleblog?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  
  redis:
    host: localhost
    port: 16379
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  mail:
    host: smtp.qq.com
    port: 587
    username: 1919737818@qq.com
    password: "******"
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true